name: Lint bicep files
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Bicep Linting
      uses: maikvandergaag/action-biceplint@v1.0.0
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bicep-lint.sarif
        category: bicep-linting