name: Lint bicep files on push
on:
  pull_request:
    branches:
    - main
  push:
    branches-ignore:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Bicep Linting
      uses: maikvandergaag/action-biceplint@v1.0.0
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bicep-lint.sarif
        category: bicep-linting